backend:
  build: .
  container_name: gb-money-tracker-backend
  environment:
    NODE_ENV: production
    PORT: 3001
    DATABASE_URL: sqlite://./money.db
    BOT_TOKEN: your_bot_token_here
  ports:
    - "3001:3001"
  restart: unless-stopped
